### ISSUE TITLE
would like to work and  find optimal solution

### ISSUE THREAD

**Issue by PranavSagar** [nanoflakes/nanoflakes-java#4]
I am new and would love to contribute

**Comment by NotJustAnna** [comment]
Hello and welcome to Nanoflakes!

I'd suggest taking a look at #1, the Hacktoberfest issue, or [nanoflakes/.github#4](https://github.com/nanoflakes/.github/issues/4), the parent Hacktoberfest issue!

Happy Hacktoberfest!
